# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/dialogs/tag_categories.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TagCategories(object):
    def setupUi(self, TagCategories):
        TagCategories.setObjectName("TagCategories")
        TagCategories.resize(628, 482)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(I("chapters.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TagCategories.setWindowIcon(icon)
        self.vboxlayout = QtWidgets.QVBoxLayout(TagCategories)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(TagCategories)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.category_box = QtWidgets.QComboBox(TagCategories)
        self.category_box.setEditable(False)
        self.category_box.setMinimumSize(QtCore.QSize(150, 0))
        self.category_box.setObjectName("category_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.category_box)
        self.label_5 = QtWidgets.QLabel(TagCategories)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.category_filter_box = QtWidgets.QComboBox(TagCategories)
        self.category_filter_box.setMinimumSize(QtCore.QSize(150, 0))
        self.category_filter_box.setObjectName("category_filter_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.category_filter_box)
        self.label_filt = QtWidgets.QLabel(TagCategories)
        self.label_filt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_filt.setObjectName("label_filt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_filt)
        self.item_filter_box = QtWidgets.QLineEdit(TagCategories)
        self.item_filter_box.setMinimumSize(QtCore.QSize(150, 0))
        self.item_filter_box.setObjectName("item_filter_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.item_filter_box)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.delete_category_button = QtWidgets.QToolButton(TagCategories)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(I("trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_category_button.setIcon(icon1)
        self.delete_category_button.setObjectName("delete_category_button")
        self.gridLayout.addWidget(self.delete_category_button, 0, 0, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.input_box = QtWidgets.QLineEdit(TagCategories)
        self.input_box.setClearButtonEnabled(True)
        self.input_box.setObjectName("input_box")
        self.hboxlayout.addWidget(self.input_box)
        self.add_category_button = QtWidgets.QToolButton(TagCategories)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(I("plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_category_button.setIcon(icon2)
        self.add_category_button.setObjectName("add_category_button")
        self.hboxlayout.addWidget(self.add_category_button)
        self.gridLayout.addLayout(self.hboxlayout, 0, 1, 1, 1)
        self.rename_category_button = QtWidgets.QToolButton(TagCategories)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(I("edit-undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rename_category_button.setIcon(icon3)
        self.rename_category_button.setObjectName("rename_category_button")
        self.gridLayout.addWidget(self.rename_category_button, 0, 2, 1, 1)
        self.apply_vl_checkbox = QtWidgets.QCheckBox(TagCategories)
        self.apply_vl_checkbox.setObjectName("apply_vl_checkbox")
        self.gridLayout.addWidget(self.apply_vl_checkbox, 1, 0, 1, 3)
        self.blank = QtWidgets.QLabel(TagCategories)
        self.blank.setText("")
        self.blank.setObjectName("blank")
        self.gridLayout.addWidget(self.blank, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 3)
        self.vboxlayout.addLayout(self.gridLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(TagCategories)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.available_items_box = QtWidgets.QListWidget(TagCategories)
        self.available_items_box.setAlternatingRowColors(True)
        self.available_items_box.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.available_items_box.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.available_items_box.setObjectName("available_items_box")
        self.gridLayout_2.addWidget(self.available_items_box, 3, 0, 1, 1)
        self.apply_button = QtWidgets.QToolButton(TagCategories)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(I("forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apply_button.setIcon(icon4)
        self.apply_button.setObjectName("apply_button")
        self.gridLayout_2.addWidget(self.apply_button, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(TagCategories)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.applied_items_box = QtWidgets.QListWidget(TagCategories)
        self.applied_items_box.setAlternatingRowColors(True)
        self.applied_items_box.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.applied_items_box.setObjectName("applied_items_box")
        self.gridLayout_2.addWidget(self.applied_items_box, 3, 2, 1, 1)
        self.unapply_button = QtWidgets.QToolButton(TagCategories)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(I("minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unapply_button.setIcon(icon5)
        self.unapply_button.setObjectName("unapply_button")
        self.gridLayout_2.addWidget(self.unapply_button, 3, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(TagCategories)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 4)
        self.vboxlayout.addLayout(self.gridLayout_2)
        self.label_3.setBuddy(self.category_box)
        self.label_5.setBuddy(self.category_filter_box)
        self.label_filt.setBuddy(self.item_filter_box)
        self.label.setBuddy(self.available_items_box)
        self.label_2.setBuddy(self.applied_items_box)

        self.retranslateUi(TagCategories)
        self.buttonBox.accepted.connect(TagCategories.accept)
        self.buttonBox.rejected.connect(TagCategories.reject)
        QtCore.QMetaObject.connectSlotsByName(TagCategories)

    def retranslateUi(self, TagCategories):

        TagCategories.setWindowTitle(_("User categories editor"))
        self.label_3.setText(_("Category &name: "))
        self.category_box.setToolTip(_("Select a category to edit"))
        self.label_5.setText(_("&Category filter: "))
        self.category_filter_box.setToolTip(_("Select the content kind of the new category"))
        self.label_filt.setText(_("Item &filter: "))
        self.item_filter_box.setToolTip(_("Enter text to filter the available items. Case and accents are ignored."))
        self.delete_category_button.setToolTip(_("Delete the current tag category"))
        self.delete_category_button.setText(_("..."))
        self.input_box.setToolTip(_("Enter a category name, then use the Add button or the Rename button"))
        self.add_category_button.setToolTip(_("Add a new category"))
        self.add_category_button.setText(_("..."))
        self.rename_category_button.setToolTip(_("Rename the current category to what is in the box"))
        self.rename_category_button.setText(_("..."))
        self.apply_vl_checkbox.setToolTip(_("<p>Show items in the Available items box only if they appear in the\n"
"            current Virtual library. Applied items not in the Virtual library will be marked\n"
"            \"not on any book\".</p>"))
        self.apply_vl_checkbox.setText(_("&Show only available items in current Virtual library"))
        self.label.setText(_("&Available items"))
        self.apply_button.setToolTip(_("Apply tags to current tag category"))
        self.apply_button.setText(_("..."))
        self.label_2.setText(_("Applied &items"))
        self.unapply_button.setToolTip(_("Unapply (remove) tag from current tag category"))
        self.unapply_button.setText(_("..."))

