.\"
.TH CALIBRE-CPMPLETE "1" "August 2021" "calibre-complete" "User Commands"
.SH NAME
calibre-complete \- run-time command line completion generator for ebook-convert(1)
.SH DESCRIPTION
This is run-time command line completion generator for ebook-convert(1)
on bash(1).
There is no needs to invoke this command by hand.
.SH "SEE ALSO"
.BR ebook-convert (1),
.BR bash (1)
