language: node_js
nodejs:
    - node
cache:
  directories:
    - node_modules
    - .build-cache

matrix:
    include:
        - os: linux
          sudo: false
          addons:
              apt:
                  packages: libgl1-mesa-dev
        - os: osx

before_install:
    - python setup/unix-ci.py install
    - python setup/unix-ci.py bootstrap

script: python setup/unix-ci.py test

notifications:
    email:
        on_success: change
        on_failure: change
