[tool.ruff]
line-length = 160
target-version = 'py38'
builtins = ['_']

[tool.ruff.lint]
ignore = ['E741', 'E402', 'E722', 'E401']
select = ['E', 'F']

[tool.ruff.lint.per-file-ignores]
"src/calibre/ebooks/unihandecode/unicodepoints.py" = ["E501"]
"src/qt/__init__.py" = ["E501"]

[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"
combine_as_imports = true
multi_line_output = 5
known_future_library = "__python__"
known_third_party = "qt"
known_standard_library = "aes,elementmaker,encodings"
known_first_party = "calibre_extensions"
