.TH "PODOFOIMGEXTRACT" "1" "2010-12-09" "PoDoFo" "podofoimgextract"
.PP
.SH NAME
podofoimgextract \- Extract all images from a PDF file
.PP
.SH SYNOPSIS
\fBpodofoimgextract\fR [inputfile] [outputdirectory]
.PP
.SH DESCRIPTION
.B podofoimgextract
is one of the command line tools from the PoDoFo library that provide several
useful operations to work with PDF files\. Itw can extract all images from a
PDF file into the specified output directory\.
.PP
.SH SEE ALSO
.BR podofobox (1),
.BR podofocolor (1),
.BR podofocountpages (1),
.BR podofocrop (1),
.BR podofoencrypt (1),
.BR podofogc (1),
.BR podofoimg2pdf (1),
.BR podofoincrementalupdates (1),
.BR podofoimpose (1),
.BR podofomerge (1),
.BR podofopages (1),
.BR podofopdfinfo (1),
.BR podofotxt2pdf (1),
.BR podofotxtextract (1),
.BR podofouncompress (1),
.BR podofoxmp (1)
.PP
.SH AUTHORS
.PP
PoDoFo is written by Dominik Seichter <domseichter@web\.de> and others\.
.PP
This manual page was written by Oleksandr Moskalenko <malex@debian\.org> for
the Debian Project (but may be used by others)\.
