.TH "PODOFOIMPOSE" "1" "2010-12-09" "PoDoFo" "podofoimpose"
.PP
.SH NAME
podofoimpose \- A powerful PDF imposition tool
.PP
.SH SYNOPSIS
\fBpodofoimpose\fR Input Output Plan [Interpreter]
.PP
.SH DESCRIPTION
.B podofoimpose
is one of the command line tools from the PoDoFo library that provide several
useful operations to work with PDF files\. It can do imposition of the final
output according to the specified imposition plan.
.PP
.SH "OPTIONS"
.PP
\fBInput\fR
.RS
PDF file or a file which contains a list of PDF file paths\.
.RE
.PP
\fBOutput\fR
.RS
Resulting PDF file\.
.RE
.PP
\fBPlan\fR
.RS
Imposition plan file\.
.RE
.PP
\fB[Interpreter]\fR
.RS
Imposition interpreter\. It can be "native" (default value) or "lua"\.
.RE
.PP
.SH SEE ALSO
.BR podofobox (1),
.BR podofocolor (1),
.BR podofocountpages (1),
.BR podofocrop (1),
.BR podofoencrypt (1),
.BR podofogc (1),
.BR podofoimg2pdf (1),
.BR podofoimgextract (1),
.BR podofomerge (1),
.BR podofoincrementalupdates (1),
.BR podofopages (1),
.BR podofopdfinfo (1),
.BR podofotxt2pdf (1),
.BR podofotxtextract (1),
.BR podofouncompress (1),
.BR podofoxmp (1)
.PP
.SH AUTHORS
.PP
PoDoFo is written by Dominik Seichter <domseichter@web\.de> and others\.
.PP
This manual page was written by Oleksandr Moskalenko <malex@debian\.org> for
the Debian Project (but may be used by others)\.
