.TH "PODOFOIMG2PDF" "1" "2010-12-09" "PoDoFo" "podofoimg2pdf"
.PP
.SH NAME
podofoimg2pdf \- Convert images to PDF files
.PP
.SH SYNOPSIS
\fBpodofoimg2pdf\fR [output\.pdf] [\-useimgsize] [image1 image2 image3 \.\.\.]
.PP
.SH DESCRIPTION
.B podofoimg2pdf
is one of the command line tools from the PoDoFo library that provide several
useful operations to work with PDF files\. This tool will combine any number
of images into a single PDF\. This is useful for creating a document from
scanned images\. Large pages will be scaled to fit the page and images smaller
than the defined page size will be centered\.
.PP
Supported image formats:
.RS
JPEG
.br
PNG
.br
TIFF
.RE
.PP
.SH OPTIONS
\fB\-useimgsize\fR
.RS
Use the image size as page size instead of A4
.RE
.PP
.SH SEE ALSO
.BR podofobox (1),
.BR podofocolor (1),
.BR podofocountpages (1),
.BR podofocrop (1),
.BR podofoencrypt (1),
.BR podofogc (1),
.BR podofoimgextract (1),
.BR podofoincrementalupdates (1),
.BR podofoimpose (1),
.BR podofomerge (1),
.BR podofopages (1),
.BR podofopdfinfo (1),
.BR podofotxt2pdf (1),
.BR podofotxtextract (1),
.BR podofouncompress (1),
.BR podofoxmp (1)
.PP
.SH AUTHORS
.PP
PoDoFo is written by Dominik Seichter <domseichter@web\.de> and others\.
.PP
This manual page was written by Oleksandr Moskalenko <malex@debian\.org> for
the Debian Project (but may be used by others)\.

