.TH "PODOFOCOLOR" "1" "2011-01-06" "PoDoFo" "podofocolor"
.PP
.SH NAME
podofocolor \- modify colors in a PDF file.
.PP
.SH SYNOPSIS
\fBpodofocolor\fR [converter] [inputfile] [outpufile]
.PP
.SH DESCRIPTION
.B podofocolor
is one of the command line tools from the PoDoFo library that provide several
useful operations to work with colors in PDF files\. It can parse and/or
modify all colors or colorspaces in a PDF file\. The
modifications can be defined via C++ or a Lua script\. Custom conversions like
\fBconvert all colors to grayscale\fR are included. Please note that only colors
of vector objects on pages and in XObjects are affected\. This tool does not
transform colos in images at the moment\.
.PP
.SH CONVERTERS
[converter] can be any of
.RS
dummy - Convert all colors to red\. Just a dummy and test implementation which
serves as an example for developers\.
.RE
.RS
grayscale - Convert all colors of vector objects in a PDF to grayscale\.
.RE
.RS
lua [script] - Convert all colors based on a Lua description\. A lua script has to be
passed as an additional parameter.
.RE
.PP
.SH "SEE ALSO"
.BR podofobox (1),
.BR podofocountpages (1),
.BR podofocrop (1),
.BR podofoencrypt (1),
.BR podofogc (1),
.BR podofoimg2pdf (1),
.BR podofoimgextract (1),
.BR podofoimpose (1),
.BR podofomerge (1),
.BR podofoincrementalupdates (1),
.BR podofopages (1),
.BR podofopdfinfo (1),
.BR podofotxt2pdf (1),
.BR podofotxtextract (1),
.BR podofouncompress (1),
.BR podofoxmp (1)
.PP
.SH AUTHOR
.PP
PoDoFo is written by Dominik Seichter <domseichter@web\.de> and others\.
.PP
This manual page was written by Dominik Seichter <domseichter@web\.de> for
the PoDoFo Project (but may be used by others)\.
