.TH "PODOFOPDFINFO" "1" "2010-12-09" "PoDoFo" "podofopdfinfo"
.PP
.SH NAME
podofopdfinfo \- provide information about a PDF file
.PP
.SH SYNOPSIS
\fBpodofopdfinfo\fR [DCPON] [inputfile]
.PP
.SH DESCRIPTION
.B podofopdfinfo
is one of the command line tools from the PoDoFo library that provide several
useful operations to work with PDF files\. It can provide a number of facts
about a PDF document according to the formatting instructions. If the
instructions are not provided, complete information is shown\.
.PP
.SH "OPTIONS"
.PP
\fBD\fR
.RS
.PP
display Document Info\.
.RE
.PP
\fBC\fR
.RS
.PP
display Classic Metadata\.
.RE
.PP
\fBP\fR
.RS
.PP
display Page Info\.
.RE
.PP
\fBO\fR
.RS
.PP
display Outlines\.
.RE
.PP
\fBN\fR
.RS
.PP
display Names\.
.RE
.PP
\fB[inputfile]\fR
.RS
.PP
Input PDF file\.
.RE
.PP
.SH SEE ALSO
.BR podofobox (1),
.BR podofocolor (1),
.BR podofocountpages (1),
.BR podofocrop (1),
.BR podofoencrypt (1),
.BR podofogc (1),
.BR podofoimg2pdf (1),
.BR podofoimgextract (1),
.BR podofoimpose (1),
.BR podofoincrementalupdates (1),
.BR podofomerge (1),
.BR podofopages (1),
.BR podofotxt2pdf (1),
.BR podofotxtextract (1),
.BR podofouncompress (1),
.BR podofoxmp (1)
.PP
.SH AUTHORS
.PP
PoDoFo is written by Dominik Seichter <domseichter@web\.de> and others\.
.PP
This manual page was written by Oleksandr Moskalenko <malex@debian\.org> for
the Debian Project (but may be used by others)\.
