# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/filename_pattern.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(335, 570)
        self.vboxlayout = QtWidgets.QVBoxLayout(Form)
        self.vboxlayout.setObjectName("vboxlayout")
        self.help_label = QtWidgets.QLabel(Form)
        self.help_label.setTextFormat(QtCore.Qt.RichText)
        self.help_label.setWordWrap(True)
        self.help_label.setOpenExternalLinks(True)
        self.help_label.setObjectName("help_label")
        self.vboxlayout.addWidget(self.help_label)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.re = QtWidgets.QComboBox(self.groupBox)
        self.re.setEditable(True)
        self.re.setMaxCount(10)
        self.re.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.re.setObjectName("re")
        self.vboxlayout1.addWidget(self.re)
        self.vboxlayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.hboxlayout1.addWidget(self.label_2)
        self.filename = QtWidgets.QLineEdit(self.groupBox_2)
        self.filename.setObjectName("filename")
        self.hboxlayout1.addWidget(self.filename)
        self.hboxlayout.addLayout(self.hboxlayout1)
        self.test_button = QtWidgets.QPushButton(self.groupBox_2)
        self.test_button.setObjectName("test_button")
        self.hboxlayout.addWidget(self.test_button)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 301, 284))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.title = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.title.setReadOnly(True)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.authors = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.authors.setReadOnly(True)
        self.authors.setObjectName("authors")
        self.gridLayout_2.addWidget(self.authors, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.series = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.series.setReadOnly(True)
        self.series.setObjectName("series")
        self.gridLayout_2.addWidget(self.series, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.series_index = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.series_index.setReadOnly(True)
        self.series_index.setObjectName("series_index")
        self.gridLayout_2.addWidget(self.series_index, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.isbn = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.isbn.setReadOnly(True)
        self.isbn.setObjectName("isbn")
        self.gridLayout_2.addWidget(self.isbn, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.publisher = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.publisher.setReadOnly(True)
        self.publisher.setObjectName("publisher")
        self.gridLayout_2.addWidget(self.publisher, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.pubdate = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.pubdate.setReadOnly(True)
        self.pubdate.setObjectName("pubdate")
        self.gridLayout_2.addWidget(self.pubdate, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)
        self.comments = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.comments.setReadOnly(True)
        self.comments.setObjectName("comments")
        self.gridLayout_2.addWidget(self.comments, 7, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.vboxlayout.addWidget(self.groupBox_2)
        self.label_2.setBuddy(self.filename)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        Form.setWindowTitle(_("Form"))
        self.help_label.setText(_("<div style=\"font-size:10pt;\">\n"
"<p>Set a regular expression pattern to use when trying to guess e-book metadata from filenames. </p>\n"
"<p>A <a href=\"%s\">tutorial</a> on using regular expressions is available.</p>\n"
"<p>Use the <b>Test</b> functionality below to test your regular expression on a few sample filenames (remember to include the file extension). The group names for the various metadata entries are documented in tooltips. Note that underscores in filenames are auto-replaced by spaces.</p></div>"))
        self.groupBox.setTitle(_("Regular &expression"))
        self.groupBox_2.setTitle(_("Test"))
        self.label_2.setText(_("File &name:"))
        self.test_button.setText(_("&Test"))
        self.label_3.setText(_("Title:"))
        self.title.setToolTip(_("Regular expression (?P&lt;title&gt;)"))
        self.title.setText(_("No match"))
        self.label_4.setText(_("Authors:"))
        self.authors.setToolTip(_("Regular expression (?P<author>)"))
        self.authors.setText(_("No match"))
        self.label_5.setText(_("Series:"))
        self.series.setToolTip(_("Regular expression (?P<series>)"))
        self.series.setText(_("No match"))
        self.label_6.setText(_("Series index:"))
        self.series_index.setToolTip(_("Regular expression (?P<series_index>)"))
        self.series_index.setText(_("No match"))
        self.label_7.setText(_("ISBN:"))
        self.isbn.setToolTip(_("Regular expression (?P<isbn>)"))
        self.isbn.setText(_("No match"))
        self.label_8.setText(_("Publisher:"))
        self.publisher.setToolTip(_("Regular expression (?P<publisher>)"))
        self.publisher.setText(_("No match"))
        self.label_9.setText(_("Published:"))
        self.pubdate.setToolTip(_("Regular expression (?P<published>)"))
        self.pubdate.setText(_("No match"))
        self.label_10.setText(_("Comments:"))
        self.comments.setToolTip(_("Regular expression (?P<comments>)"))
        self.comments.setText(_("No match"))

