usr/bin
#usr/lib/udev lib/ # udev rules are useless right now
#
# matches other than "usr/lib/calibre/calibre/plugins/"
usr/lib/calibre/calibre/[!p]*/
usr/lib/calibre/calibre/*.py
#
usr/lib/calibre/sgmllib.py
usr/lib/calibre/odf
usr/lib/calibre/templite
usr/lib/calibre/tinycss
usr/lib/calibre/css_selectors
usr/lib/calibre/polyglot
usr/share/
icons/favicon.ico usr/share/calibre/content-server/
debian/calibre.rtupdate usr/share/python3/runtime.d/
