usr/bin
#usr/lib/udev lib/ # udev rules are useless right now
usr/lib/calibre/calibre/
usr/lib/calibre/odf
usr/lib/calibre/templite
usr/lib/calibre/html5lib
usr/lib/calibre/regex
usr/lib/calibre/tinycss
usr/lib/calibre/css_selectors
usr/lib/calibre/duktape
usr/lib/calibre/lzma
usr/share/
../local/*.desktop usr/share/applications
../local/mime/*.xml usr/share/mime/packages/
icons/favicon.ico usr/share/calibre/content-server/
