# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/preferences/plugins.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(723, 540)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search = SearchBox2(Form)
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.next_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(I("arrow-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_button.setIcon(icon)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.previous_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_button.sizePolicy().hasHeightForWidth())
        self.previous_button.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(I("arrow-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_button.setIcon(icon1)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout.addWidget(self.previous_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.user_installed_plugins = QtWidgets.QCheckBox(Form)
        self.user_installed_plugins.setObjectName("user_installed_plugins")
        self.verticalLayout.addWidget(self.user_installed_plugins)
        self.plugin_view = QtWidgets.QTreeView(Form)
        self.plugin_view.setAlternatingRowColors(True)
        self.plugin_view.setIconSize(QtCore.QSize(32, 32))
        self.plugin_view.setAnimated(True)
        self.plugin_view.setWordWrap(True)
        self.plugin_view.setHeaderHidden(True)
        self.plugin_view.setObjectName("plugin_view")
        self.verticalLayout.addWidget(self.plugin_view)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toggle_plugin_button = QtWidgets.QPushButton(Form)
        self.toggle_plugin_button.setObjectName("toggle_plugin_button")
        self.horizontalLayout_6.addWidget(self.toggle_plugin_button)
        self.customize_plugin_button = QtWidgets.QPushButton(Form)
        self.customize_plugin_button.setObjectName("customize_plugin_button")
        self.horizontalLayout_6.addWidget(self.customize_plugin_button)
        self.remove_plugin_button = QtWidgets.QPushButton(Form)
        self.remove_plugin_button.setObjectName("remove_plugin_button")
        self.horizontalLayout_6.addWidget(self.remove_plugin_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_plugin_new = QtWidgets.QPushButton(Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(I("plugins/plugin_new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_plugin_new.setIcon(icon2)
        self.button_plugin_new.setObjectName("button_plugin_new")
        self.horizontalLayout_7.addWidget(self.button_plugin_new)
        self.button_plugin_updates = QtWidgets.QPushButton(Form)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(I("plugins/plugin_updater.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_plugin_updates.setIcon(icon3)
        self.button_plugin_updates.setObjectName("button_plugin_updates")
        self.horizontalLayout_7.addWidget(self.button_plugin_updates)
        self.button_plugin_add = QtWidgets.QPushButton(Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(I("document_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_plugin_add.setIcon(icon4)
        self.button_plugin_add.setObjectName("button_plugin_add")
        self.horizontalLayout_7.addWidget(self.button_plugin_add)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        Form.setWindowTitle(_("Form"))
        self.label_8.setText(_("Here you can customize the behavior of calibre by controlling what plugins it uses."))
        self.next_button.setText(_("&Next"))
        self.previous_button.setText(_("&Previous"))
        self.user_installed_plugins.setToolTip(_("Show only those plugins that have been installed by you"))
        self.user_installed_plugins.setText(_("Show only &user installed plugins"))
        self.toggle_plugin_button.setText(_("Enable/&disable plugin"))
        self.customize_plugin_button.setText(_("&Customize plugin"))
        self.remove_plugin_button.setText(_("&Remove plugin"))
        self.button_plugin_new.setText(_("Get &new plugins"))
        self.button_plugin_updates.setText(_("Check for &updated plugins"))
        self.button_plugin_add.setText(_("&Load plugin from file"))

from calibre.gui2.search_box import SearchBox2

