# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/preferences/search.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(788, 663)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.clear_history_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_history_button.sizePolicy().hasHeightForWidth())
        self.clear_history_button.setSizePolicy(sizePolicy)
        self.clear_history_button.setObjectName("clear_history_button")
        self.gridLayout_6.addWidget(self.clear_history_button, 6, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.opt_limit_search_columns = QtWidgets.QCheckBox(self.groupBox)
        self.opt_limit_search_columns.setObjectName("opt_limit_search_columns")
        self.gridLayout_2.addWidget(self.opt_limit_search_columns, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.opt_limit_search_columns_to = EditWithComplete(self.groupBox)
        self.opt_limit_search_columns_to.setObjectName("opt_limit_search_columns_to")
        self.gridLayout_2.addWidget(self.opt_limit_search_columns_to, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox, 5, 0, 1, 2)
        self.opt_search_as_you_type = QtWidgets.QCheckBox(self.tab)
        self.opt_search_as_you_type.setObjectName("opt_search_as_you_type")
        self.gridLayout_6.addWidget(self.opt_search_as_you_type, 0, 0, 1, 2)
        self.opt_case_sensitive = QtWidgets.QCheckBox(self.tab)
        self.opt_case_sensitive.setObjectName("opt_case_sensitive")
        self.gridLayout_6.addWidget(self.opt_case_sensitive, 3, 0, 1, 1)
        self.opt_highlight_search_matches = QtWidgets.QCheckBox(self.tab)
        self.opt_highlight_search_matches.setObjectName("opt_highlight_search_matches")
        self.gridLayout_6.addWidget(self.opt_highlight_search_matches, 1, 0, 1, 2)
        self.opt_show_highlight_toggle_button = QtWidgets.QCheckBox(self.tab)
        self.opt_show_highlight_toggle_button.setObjectName("opt_show_highlight_toggle_button")
        self.gridLayout_6.addWidget(self.opt_show_highlight_toggle_button, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 7, 0, 1, 1)
        self.opt_use_primary_find_in_search = QtWidgets.QCheckBox(self.tab)
        self.opt_use_primary_find_in_search.setObjectName("opt_use_primary_find_in_search")
        self.gridLayout_6.addWidget(self.opt_use_primary_find_in_search, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l12 = QtWidgets.QGridLayout()
        self.l12.setObjectName("l12")
        self.la10 = QtWidgets.QLabel(self.groupBox_2)
        self.la10.setObjectName("la10")
        self.l12.addWidget(self.la10, 0, 0, 1, 1)
        self.gst_names = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gst_names.sizePolicy().hasHeightForWidth())
        self.gst_names.setSizePolicy(sizePolicy)
        self.gst_names.setEditable(True)
        self.gst_names.setMinimumContentsLength(10)
        self.gst_names.setObjectName("gst_names")
        self.l12.addWidget(self.gst_names, 0, 1, 1, 1)
        self.gst_delete_button = QtWidgets.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(I("trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gst_delete_button.setIcon(icon)
        self.gst_delete_button.setObjectName("gst_delete_button")
        self.l12.addWidget(self.gst_delete_button, 0, 2, 1, 1)
        self.la112 = QtWidgets.QLabel(self.groupBox_2)
        self.la112.setObjectName("la112")
        self.l12.addWidget(self.la112, 1, 0, 1, 1)
        self.gst_value = EditWithComplete(self.groupBox_2)
        self.gst_value.setObjectName("gst_value")
        self.l12.addWidget(self.gst_value, 1, 1, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.gst_save_button = QtWidgets.QToolButton(self.groupBox_2)
        self.gst_save_button.setObjectName("gst_save_button")
        self.hboxlayout.addWidget(self.gst_save_button)
        self.l12.addLayout(self.hboxlayout, 2, 0, 1, 3)
        self.gridLayout_3.addLayout(self.l12, 0, 0, 1, 1)
        self.gst_explanation = QtWidgets.QTextBrowser(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.gst_explanation.sizePolicy().hasHeightForWidth())
        self.gst_explanation.setSizePolicy(sizePolicy)
        self.gst_explanation.setObjectName("gst_explanation")
        self.gridLayout_3.addWidget(self.gst_explanation, 0, 1, 3, 1)
        self.user_category_layout = QtWidgets.QHBoxLayout()
        self.user_category_layout.setObjectName("user_category_layout")
        self.l11 = QtWidgets.QLabel(self.groupBox_2)
        self.l11.setObjectName("l11")
        self.user_category_layout.addWidget(self.l11)
        self.opt_grouped_search_make_user_categories = EditWithComplete(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_grouped_search_make_user_categories.sizePolicy().hasHeightForWidth())
        self.opt_grouped_search_make_user_categories.setSizePolicy(sizePolicy)
        self.opt_grouped_search_make_user_categories.setObjectName("opt_grouped_search_make_user_categories")
        self.user_category_layout.addWidget(self.opt_grouped_search_make_user_categories)
        self.gridLayout_3.addLayout(self.user_category_layout, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox22 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox22.setObjectName("groupBox22")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox22)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label1 = QtWidgets.QLabel(self.groupBox22)
        self.label1.setWordWrap(True)
        self.label1.setObjectName("label1")
        self.gridLayout_22.addWidget(self.label1, 0, 0, 1, 6)
        self.label_221 = QtWidgets.QLabel(self.groupBox22)
        self.label_221.setObjectName("label_221")
        self.gridLayout_22.addWidget(self.label_221, 1, 0, 1, 1)
        self.similar_authors_search_key = QtWidgets.QComboBox(self.groupBox22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.similar_authors_search_key.sizePolicy().hasHeightForWidth())
        self.similar_authors_search_key.setSizePolicy(sizePolicy)
        self.similar_authors_search_key.setObjectName("similar_authors_search_key")
        self.gridLayout_22.addWidget(self.similar_authors_search_key, 1, 1, 1, 1)
        self.opt_similar_authors_match_kind = QtWidgets.QComboBox(self.groupBox22)
        self.opt_similar_authors_match_kind.setObjectName("opt_similar_authors_match_kind")
        self.gridLayout_22.addWidget(self.opt_similar_authors_match_kind, 1, 2, 1, 1)
        self.label_222 = QtWidgets.QLabel(self.groupBox22)
        self.label_222.setObjectName("label_222")
        self.gridLayout_22.addWidget(self.label_222, 1, 3, 1, 1)
        self.similar_series_search_key = QtWidgets.QComboBox(self.groupBox22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.similar_series_search_key.sizePolicy().hasHeightForWidth())
        self.similar_series_search_key.setSizePolicy(sizePolicy)
        self.similar_series_search_key.setObjectName("similar_series_search_key")
        self.gridLayout_22.addWidget(self.similar_series_search_key, 1, 4, 1, 1)
        self.opt_similar_series_match_kind = QtWidgets.QComboBox(self.groupBox22)
        self.opt_similar_series_match_kind.setObjectName("opt_similar_series_match_kind")
        self.gridLayout_22.addWidget(self.opt_similar_series_match_kind, 1, 5, 1, 1)
        self.label_223 = QtWidgets.QLabel(self.groupBox22)
        self.label_223.setObjectName("label_223")
        self.gridLayout_22.addWidget(self.label_223, 2, 0, 1, 1)
        self.similar_tags_search_key = QtWidgets.QComboBox(self.groupBox22)
        self.similar_tags_search_key.setObjectName("similar_tags_search_key")
        self.gridLayout_22.addWidget(self.similar_tags_search_key, 2, 1, 1, 1)
        self.opt_similar_tags_match_kind = QtWidgets.QComboBox(self.groupBox22)
        self.opt_similar_tags_match_kind.setObjectName("opt_similar_tags_match_kind")
        self.gridLayout_22.addWidget(self.opt_similar_tags_match_kind, 2, 2, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.groupBox22)
        self.label_224.setObjectName("label_224")
        self.gridLayout_22.addWidget(self.label_224, 2, 3, 1, 1)
        self.similar_publisher_search_key = QtWidgets.QComboBox(self.groupBox22)
        self.similar_publisher_search_key.setObjectName("similar_publisher_search_key")
        self.gridLayout_22.addWidget(self.similar_publisher_search_key, 2, 4, 1, 1)
        self.opt_similar_publisher_match_kind = QtWidgets.QComboBox(self.groupBox22)
        self.opt_similar_publisher_match_kind.setObjectName("opt_similar_publisher_match_kind")
        self.gridLayout_22.addWidget(self.opt_similar_publisher_match_kind, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem2, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox22, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_2.setBuddy(self.opt_limit_search_columns_to)
        self.la10.setBuddy(self.gst_names)
        self.la112.setBuddy(self.gst_value)
        self.l11.setBuddy(self.opt_grouped_search_make_user_categories)
        self.label_221.setBuddy(self.similar_authors_search_key)
        self.label_222.setBuddy(self.similar_series_search_key)
        self.label_223.setBuddy(self.similar_tags_search_key)
        self.label_224.setBuddy(self.similar_publisher_search_key)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        Form.setWindowTitle(_("Form"))
        self.clear_history_button.setToolTip(_("Clear search histories from all over calibre. Including the book list, E-book viewer, fetch news dialog, etc."))
        self.clear_history_button.setText(_("Clear search &histories"))
        self.groupBox.setTitle(_("What to search by default"))
        self.label.setText(_("When you enter a search term without a prefix, by default calibre will search all metadata for matches. For example, entering, \"asimov\" will search not just authors but title/tags/series/comments/etc. Use these options if you would like to change this behavior."))
        self.opt_limit_search_columns.setText(_("&Limit the searched metadata"))
        self.label_2.setText(_("&Columns that non-prefixed searches are limited to:"))
        self.label_3.setText(_("Note that this option affects all searches, including saved searches and restrictions. Therefore, if you use this option, it is best to ensure that you always use prefixes in your saved searches. For example, use \"series:Foundation\" rather than just \"Foundation\" in  a saved search"))
        self.opt_search_as_you_type.setText(_("Search as you &type"))
        self.opt_case_sensitive.setText(_("Case &sensitive searching"))
        self.opt_highlight_search_matches.setText(_("&Highlight search results instead of restricting the book list to the results"))
        self.opt_show_highlight_toggle_button.setToolTip(_("<p>This option will cause a small button to appear next to the Search bar. Clicking the button will toggle between showing only the search results and showing all books with the search results highlighted."))
        self.opt_show_highlight_toggle_button.setText(_("Show a &quick toggle button to switch between highlighting and restricting results next to the Search bar"))
        self.opt_use_primary_find_in_search.setText(_("Unaccented characters match &accented characters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Genera&l"))
        self.groupBox_2.setTitle(_("Grouped search terms"))
        self.la10.setText(_("&Names:"))
        self.gst_names.setToolTip(_("Contains the names of the currently-defined group search terms.\n"
"Create a new name by entering it into the empty box, then\n"
"pressing Save. Rename a search term by selecting it then\n"
"changing the name and pressing Save. Change the value of\n"
"a search term by changing the value box then pressing Save."))
        self.gst_delete_button.setToolTip(_("Delete the current search term"))
        self.gst_delete_button.setText(_("..."))
        self.la112.setText(_("&Value:"))
        self.gst_value.setToolTip(_("Enter a comma-separated list of lookup names of the columns\n"
"to include in the grouped search term"))
        self.gst_save_button.setToolTip(_("Save the current search term. You can rename a search term by\n"
"changing the name then pressing Save. You can change the value\n"
"of a search term by changing the value box then pressing Save."))
        self.gst_save_button.setText(_("&Save"))
        self.l11.setText(_("Make &user categories from:"))
        self.opt_grouped_search_make_user_categories.setToolTip(_("Enter the names of any grouped search terms you wish\n"
"to be shown as user categories"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("&Grouped searches"))
        self.groupBox22.setTitle(_("What to search when searching similar books"))
        self.label1.setText(_("<p>When you search for similar books by right clicking the\n"
"         book and selecting \"Similar books...\",\n"
"         calibre constructs a search using the column lookup names specified below.\n"
"         By changing the lookup name to a grouped search term you can\n"
"         search multiple columns at once.</p>"))
        self.label_221.setText(_("S&imilar authors: "))
        self.label_222.setText(_("Si&milar series: "))
        self.label_223.setText(_("Similar &tags: "))
        self.label_224.setText(_("Simi&lar publishers: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _("&Similar books"))

from calibre.gui2.complete2 import EditWithComplete

