# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/viewer/config.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(839, 630)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(I("config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabs = QtWidgets.QTabWidget(Dialog)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border-radius: 5px;\n"
"     color: black;\n"
"     font-weight: bold;\n"
" }\n"
"\n"
" QToolBox::tab:selected {\n"
"     font-style: italic;\n"
" }\n"
"\n"
"QToolBox::tab:hover {\n"
"   color: red;\n"
"   font-style: italic;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 799, 354))
        self.page.setObjectName("page")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.serif_family = QtWidgets.QFontComboBox(self.page)
        self.serif_family.setObjectName("serif_family")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.serif_family)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sans_family = QtWidgets.QFontComboBox(self.page)
        self.sans_family.setObjectName("sans_family")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sans_family)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.mono_family = QtWidgets.QFontComboBox(self.page)
        self.mono_family.setObjectName("mono_family")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mono_family)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.default_font_size = QtWidgets.QSpinBox(self.page)
        self.default_font_size.setMinimum(8)
        self.default_font_size.setMaximum(100)
        self.default_font_size.setObjectName("default_font_size")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.default_font_size)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.mono_font_size = QtWidgets.QSpinBox(self.page)
        self.mono_font_size.setMinimum(8)
        self.mono_font_size.setMaximum(100)
        self.mono_font_size.setObjectName("mono_font_size")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mono_font_size)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.standard_font = QtWidgets.QComboBox(self.page)
        self.standard_font.setObjectName("standard_font")
        self.standard_font.addItem("")
        self.standard_font.addItem("")
        self.standard_font.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.standard_font)
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.opt_font_mag_step = QtWidgets.QSpinBox(self.page)
        self.opt_font_mag_step.setObjectName("opt_font_mag_step")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.opt_font_mag_step)
        self.label_22 = QtWidgets.QLabel(self.page)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.minimum_font_size = QtWidgets.QSpinBox(self.page)
        self.minimum_font_size.setMinimum(8)
        self.minimum_font_size.setObjectName("minimum_font_size")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.minimum_font_size)
        self.toolBox.addItem(self.page, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 371, 312))
        self.page_5.setObjectName("page_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.page_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_8)
        self.line = QtWidgets.QFrame(self.page_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label_27 = QtWidgets.QLabel(self.page_5)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.opt_cols_per_screen_portrait = QtWidgets.QSpinBox(self.page_5)
        self.opt_cols_per_screen_portrait.setMinimum(1)
        self.opt_cols_per_screen_portrait.setMaximum(5)
        self.opt_cols_per_screen_portrait.setObjectName("opt_cols_per_screen_portrait")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.opt_cols_per_screen_portrait)
        self.opt_override_book_margins = QtWidgets.QCheckBox(self.page_5)
        self.opt_override_book_margins.setChecked(True)
        self.opt_override_book_margins.setObjectName("opt_override_book_margins")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.opt_override_book_margins)
        self.label_18 = QtWidgets.QLabel(self.page_5)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.opt_top_margin = QtWidgets.QSpinBox(self.page_5)
        self.opt_top_margin.setMinimum(10)
        self.opt_top_margin.setMaximum(1000)
        self.opt_top_margin.setObjectName("opt_top_margin")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.opt_top_margin)
        self.label_19 = QtWidgets.QLabel(self.page_5)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.opt_side_margin = QtWidgets.QSpinBox(self.page_5)
        self.opt_side_margin.setMinimum(10)
        self.opt_side_margin.setMaximum(1000)
        self.opt_side_margin.setObjectName("opt_side_margin")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.opt_side_margin)
        self.label_17 = QtWidgets.QLabel(self.page_5)
        self.label_17.setObjectName("label_17")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.opt_bottom_margin = QtWidgets.QSpinBox(self.page_5)
        self.opt_bottom_margin.setMinimum(10)
        self.opt_bottom_margin.setMaximum(1000)
        self.opt_bottom_margin.setObjectName("opt_bottom_margin")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.opt_bottom_margin)
        self.line_2 = QtWidgets.QFrame(self.page_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.label_13 = QtWidgets.QLabel(self.page_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_13)
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setObjectName("label_28")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.opt_cols_per_screen_landscape = QtWidgets.QSpinBox(self.page_5)
        self.opt_cols_per_screen_landscape.setMinimum(1)
        self.opt_cols_per_screen_landscape.setMaximum(5)
        self.opt_cols_per_screen_landscape.setObjectName("opt_cols_per_screen_landscape")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.opt_cols_per_screen_landscape)
        self.toolBox.addItem(self.page_5, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 395, 212))
        self.page_2.setObjectName("page_2")
        self.formLayout = QtWidgets.QFormLayout(self.page_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.max_fs_width = QtWidgets.QSpinBox(self.page_2)
        self.max_fs_width.setMinimum(100)
        self.max_fs_width.setMaximum(10000)
        self.max_fs_width.setObjectName("max_fs_width")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.max_fs_width)
        self.opt_fullscreen_pos = QtWidgets.QCheckBox(self.page_2)
        self.opt_fullscreen_pos.setObjectName("opt_fullscreen_pos")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.opt_fullscreen_pos)
        self.opt_fullscreen_scrollbar = QtWidgets.QCheckBox(self.page_2)
        self.opt_fullscreen_scrollbar.setObjectName("opt_fullscreen_scrollbar")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.opt_fullscreen_scrollbar)
        self.opt_start_in_fullscreen = QtWidgets.QCheckBox(self.page_2)
        self.opt_start_in_fullscreen.setObjectName("opt_start_in_fullscreen")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.opt_start_in_fullscreen)
        self.opt_show_fullscreen_help = QtWidgets.QCheckBox(self.page_2)
        self.opt_show_fullscreen_help.setObjectName("opt_show_fullscreen_help")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.opt_show_fullscreen_help)
        self.label_24 = QtWidgets.QLabel(self.page_2)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.opt_fullscreen_clock = QtWidgets.QCheckBox(self.page_2)
        self.opt_fullscreen_clock.setObjectName("opt_fullscreen_clock")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.opt_fullscreen_clock)
        self.max_fs_height = QtWidgets.QSpinBox(self.page_2)
        self.max_fs_height.setMinimum(100)
        self.max_fs_height.setMaximum(10000)
        self.max_fs_height.setSingleStep(25)
        self.max_fs_height.setObjectName("max_fs_height")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.max_fs_height)
        self.toolBox.addItem(self.page_2, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 349, 76))
        self.page_6.setObjectName("page_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.page_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.background_color_sample = QtWidgets.QLabel(self.page_6)
        self.background_color_sample.setObjectName("background_color_sample")
        self.horizontalLayout.addWidget(self.background_color_sample)
        self.change_background_color_button = QtWidgets.QPushButton(self.page_6)
        self.change_background_color_button.setObjectName("change_background_color_button")
        self.horizontalLayout.addWidget(self.change_background_color_button)
        self.reset_background_color_button = QtWidgets.QPushButton(self.page_6)
        self.reset_background_color_button.setObjectName("reset_background_color_button")
        self.horizontalLayout.addWidget(self.reset_background_color_button)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_color_sample = QtWidgets.QLabel(self.page_6)
        self.text_color_sample.setObjectName("text_color_sample")
        self.horizontalLayout_2.addWidget(self.text_color_sample)
        self.change_text_color_button = QtWidgets.QPushButton(self.page_6)
        self.change_text_color_button.setObjectName("change_text_color_button")
        self.horizontalLayout_2.addWidget(self.change_text_color_button)
        self.reset_text_color_button = QtWidgets.QPushButton(self.page_6)
        self.reset_text_color_button.setObjectName("reset_text_color_button")
        self.horizontalLayout_2.addWidget(self.reset_text_color_button)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.toolBox.addItem(self.page_6, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 799, 354))
        self.page_3.setObjectName("page_3")
        self.vlayout123 = QtWidgets.QVBoxLayout(self.page_3)
        self.vlayout123.setContentsMargins(0, 0, 0, 0)
        self.vlayout123.setObjectName("vlayout123")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.opt_page_flip_duration = QtWidgets.QDoubleSpinBox(self.page_3)
        self.opt_page_flip_duration.setDecimals(1)
        self.opt_page_flip_duration.setMinimum(0.1)
        self.opt_page_flip_duration.setMaximum(3.0)
        self.opt_page_flip_duration.setSingleStep(0.1)
        self.opt_page_flip_duration.setProperty("value", 0.5)
        self.opt_page_flip_duration.setObjectName("opt_page_flip_duration")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.opt_page_flip_duration)
        self.opt_tap_flips_pages = QtWidgets.QCheckBox(self.page_3)
        self.opt_tap_flips_pages.setObjectName("opt_tap_flips_pages")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.opt_tap_flips_pages)
        self.opt_wheel_flips_pages = QtWidgets.QCheckBox(self.page_3)
        self.opt_wheel_flips_pages.setObjectName("opt_wheel_flips_pages")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.opt_wheel_flips_pages)
        self.opt_line_scrolling_stops_on_pagebreaks = QtWidgets.QCheckBox(self.page_3)
        self.opt_line_scrolling_stops_on_pagebreaks.setObjectName("opt_line_scrolling_stops_on_pagebreaks")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.opt_line_scrolling_stops_on_pagebreaks)
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.opt_wheel_scroll_fraction = QtWidgets.QSpinBox(self.groupBox)
        self.opt_wheel_scroll_fraction.setMinimum(1)
        self.opt_wheel_scroll_fraction.setMaximum(100)
        self.opt_wheel_scroll_fraction.setSingleStep(5)
        self.opt_wheel_scroll_fraction.setObjectName("opt_wheel_scroll_fraction")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.opt_wheel_scroll_fraction)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.opt_line_scroll_fraction = QtWidgets.QSpinBox(self.groupBox)
        self.opt_line_scroll_fraction.setMinimum(1)
        self.opt_line_scroll_fraction.setMaximum(100)
        self.opt_line_scroll_fraction.setSingleStep(5)
        self.opt_line_scroll_fraction.setObjectName("opt_line_scroll_fraction")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.opt_line_scroll_fraction)
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.vlayout123.addLayout(self.formLayout_4)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 505, 304))
        self.page_4.setObjectName("page_4")
        self.gridLayout = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.hyphenate = QtWidgets.QCheckBox(self.page_4)
        self.hyphenate.setObjectName("hyphenate")
        self.gridLayout.addWidget(self.hyphenate, 0, 0, 1, 2)
        self.hyphenate_label = QtWidgets.QLabel(self.page_4)
        self.hyphenate_label.setObjectName("hyphenate_label")
        self.gridLayout.addWidget(self.hyphenate_label, 1, 0, 1, 1)
        self.hyphenate_default_lang = QtWidgets.QComboBox(self.page_4)
        self.hyphenate_default_lang.setObjectName("hyphenate_default_lang")
        self.gridLayout.addWidget(self.hyphenate_default_lang, 1, 1, 1, 1)
        self.opt_show_controls = QtWidgets.QCheckBox(self.page_4)
        self.opt_show_controls.setObjectName("opt_show_controls")
        self.gridLayout.addWidget(self.opt_show_controls, 2, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 3, 0, 1, 1)
        self.search_online_url = QtWidgets.QLineEdit(self.page_4)
        self.search_online_url.setObjectName("search_online_url")
        self.gridLayout.addWidget(self.search_online_url, 3, 1, 1, 1)
        self.opt_remember_window_size = QtWidgets.QCheckBox(self.page_4)
        self.opt_remember_window_size.setObjectName("opt_remember_window_size")
        self.gridLayout.addWidget(self.opt_remember_window_size, 4, 0, 1, 2)
        self.opt_remember_current_page = QtWidgets.QCheckBox(self.page_4)
        self.opt_remember_current_page.setObjectName("opt_remember_current_page")
        self.gridLayout.addWidget(self.opt_remember_current_page, 5, 0, 1, 2)
        self.opt_copy_bookmarks_to_file = QtWidgets.QCheckBox(self.page_4)
        self.opt_copy_bookmarks_to_file.setObjectName("opt_copy_bookmarks_to_file")
        self.gridLayout.addWidget(self.opt_copy_bookmarks_to_file, 6, 0, 1, 2)
        self.opt_singleinstance = QtWidgets.QCheckBox(self.page_4)
        self.opt_singleinstance.setObjectName("opt_singleinstance")
        self.gridLayout.addWidget(self.opt_singleinstance, 7, 0, 1, 2)
        self.opt_fit_images = QtWidgets.QCheckBox(self.page_4)
        self.opt_fit_images.setObjectName("opt_fit_images")
        self.gridLayout.addWidget(self.opt_fit_images, 8, 0, 1, 2)
        self.clear_search_history_button = QtWidgets.QPushButton(self.page_4)
        self.clear_search_history_button.setObjectName("clear_search_history_button")
        self.gridLayout.addWidget(self.clear_search_history_button, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setWordWrap(True)
        self.label_10.setOpenExternalLinks(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.css = QtWidgets.QPlainTextEdit(self.tab_3)
        self.css.setObjectName("css")
        self.verticalLayout_3.addWidget(self.css)
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayout_7 = QtWidgets.QFormLayout(self.tab_4)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setObjectName("label_23")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_23)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_7.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.save_theme_button = QtWidgets.QToolButton(self.tab_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(I("save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_theme_button.setIcon(icon1)
        self.save_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.save_theme_button.setObjectName("save_theme_button")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.save_theme_button)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.load_theme_button = QtWidgets.QToolButton(self.tab_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(I("document_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_theme_button.setIcon(icon2)
        self.load_theme_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.load_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.load_theme_button.setObjectName("load_theme_button")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.load_theme_button)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.delete_theme_button = QtWidgets.QToolButton(self.tab_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(I("trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_theme_button.setIcon(icon3)
        self.delete_theme_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.delete_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_theme_button.setObjectName("delete_theme_button")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.delete_theme_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_7.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.theming_message = QtWidgets.QLabel(self.tab_4)
        self.theming_message.setText("")
        self.theming_message.setObjectName("theming_message")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.theming_message)
        self.tabs.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.dictionary_list = QtWidgets.QListWidget(self.tab_5)
        self.dictionary_list.setObjectName("dictionary_list")
        self.verticalLayout_4.addWidget(self.dictionary_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_dictionary_website_button = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_dictionary_website_button.sizePolicy().hasHeightForWidth())
        self.add_dictionary_website_button.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(I("plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_dictionary_website_button.setIcon(icon4)
        self.add_dictionary_website_button.setObjectName("add_dictionary_website_button")
        self.horizontalLayout_3.addWidget(self.add_dictionary_website_button)
        self.remove_dictionary_website_button = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_dictionary_website_button.sizePolicy().hasHeightForWidth())
        self.remove_dictionary_website_button.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(I("minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_dictionary_website_button.setIcon(icon5)
        self.remove_dictionary_website_button.setObjectName("remove_dictionary_website_button")
        self.horizontalLayout_3.addWidget(self.remove_dictionary_website_button)
        self.change_dictionary_website_button = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_dictionary_website_button.sizePolicy().hasHeightForWidth())
        self.change_dictionary_website_button.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(I("edit_input.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_dictionary_website_button.setIcon(icon6)
        self.change_dictionary_website_button.setObjectName("change_dictionary_website_button")
        self.horizontalLayout_3.addWidget(self.change_dictionary_website_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabs.addTab(self.tab_5, "")
        self.gridLayout_4.addWidget(self.tabs, 0, 0, 1, 1)
        self.label.setBuddy(self.serif_family)
        self.label_2.setBuddy(self.sans_family)
        self.label_3.setBuddy(self.mono_family)
        self.label_4.setBuddy(self.default_font_size)
        self.label_5.setBuddy(self.mono_font_size)
        self.label_6.setBuddy(self.standard_font)
        self.label_12.setBuddy(self.opt_font_mag_step)
        self.label_22.setBuddy(self.minimum_font_size)
        self.label_27.setBuddy(self.opt_cols_per_screen_portrait)
        self.label_18.setBuddy(self.opt_top_margin)
        self.label_19.setBuddy(self.opt_side_margin)
        self.label_17.setBuddy(self.opt_bottom_margin)
        self.label_28.setBuddy(self.opt_cols_per_screen_landscape)
        self.label_7.setBuddy(self.max_fs_width)
        self.label_11.setBuddy(self.opt_page_flip_duration)
        self.label_29.setBuddy(self.opt_wheel_scroll_fraction)
        self.label_30.setBuddy(self.opt_line_scroll_fraction)
        self.hyphenate_label.setBuddy(self.hyphenate_default_lang)
        self.label_26.setBuddy(self.search_online_url)
        self.label_15.setBuddy(self.save_theme_button)
        self.label_20.setBuddy(self.load_theme_button)

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.hyphenate.toggled['bool'].connect(self.hyphenate_default_lang.setEnabled)
        self.opt_override_book_margins.toggled['bool'].connect(self.opt_top_margin.setEnabled)
        self.opt_override_book_margins.toggled['bool'].connect(self.opt_side_margin.setEnabled)
        self.opt_override_book_margins.toggled['bool'].connect(self.opt_bottom_margin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):

        Dialog.setWindowTitle(_("Configure E-book viewer"))
        self.label.setText(_("Se&rif family:"))
        self.label_2.setText(_("&Sans family:"))
        self.label_3.setText(_("&Monospace family:"))
        self.label_4.setText(_("&Default font size:"))
        self.default_font_size.setSuffix(_(" px"))
        self.label_5.setText(_("Monospace &font size:"))
        self.mono_font_size.setSuffix(_(" px"))
        self.label_6.setText(_("S&tandard font:"))
        self.standard_font.setItemText(0, _("Serif"))
        self.standard_font.setItemText(1, _("Sans-serif"))
        self.standard_font.setItemText(2, _("Monospace"))
        self.label_12.setText(_("Font &magnification step size:"))
        self.opt_font_mag_step.setToolTip(_("The amount by which the font size is increased/decreased\n"
" when you click the font size larger/smaller buttons"))
        self.opt_font_mag_step.setSuffix(_("%"))
        self.label_22.setText(_("Minimum font si&ze:"))
        self.minimum_font_size.setToolTip(_("The minimum font size in pixels"))
        self.minimum_font_size.setSuffix(_(" px"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _("&Font options"))
        self.label_8.setText(_("<p>These options only apply in \"paged\" mode, where the text is broken up into pages, as in a paper book. To get into this mode, use the button with the yellow scroll icon in the top right corner of the viewer window."))
        self.label_27.setText(_("In &portrait orientation:"))
        self.opt_cols_per_screen_portrait.setToolTip(_("Controls the number of pages on the screen when the viewer window\'s width is less than its height"))
        self.opt_override_book_margins.setText(_("&Override the page margin settings specified in the book"))
        self.label_18.setText(_("&Top margin:"))
        self.opt_top_margin.setSuffix(_(" px"))
        self.label_19.setText(_("&Side margin:"))
        self.opt_side_margin.setSuffix(_(" px"))
        self.label_17.setText(_("&Bottom margin:"))
        self.opt_bottom_margin.setSuffix(_(" px"))
        self.label_13.setText(_("The number of pages of text to show on screen "))
        self.label_28.setText(_("In &landscape orientation: "))
        self.opt_cols_per_screen_landscape.setToolTip(_("Controls the number of pages on the screen when the viewer window\'s height is less than its width"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _("Text &layout in paged mode"))
        self.label_7.setText(_("Maximum text width in &fullscreen:"))
        self.max_fs_width.setToolTip(_("Set the maximum width that the book\'s text and pictures will take when in fullscreen mode. This allows you to read the book text without it becoming too wide."))
        self.max_fs_width.setSuffix(_(" px"))
        self.opt_fullscreen_pos.setText(_("Show reading &position in full screen mode"))
        self.opt_fullscreen_scrollbar.setText(_("Show &scrollbar in full screen mode"))
        self.opt_start_in_fullscreen.setText(_("&Start viewer in full screen mode"))
        self.opt_show_fullscreen_help.setText(_("Show &help message when starting full screen mode"))
        self.label_24.setText(_("Maximum text height in fullscreen (paged mode):"))
        self.opt_fullscreen_clock.setText(_("Show &clock in full screen mode"))
        self.max_fs_height.setSpecialValueText(_("Disabled"))
        self.max_fs_height.setSuffix(_(" px"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _("F&ull screen options"))
        self.label_14.setText(_("Background color:"))
        self.background_color_sample.setText(_("Sample"))
        self.change_background_color_button.setText(_("&Change"))
        self.reset_background_color_button.setText(_("&Reset"))
        self.label_16.setText(_("Text color:"))
        self.text_color_sample.setText(_("Sample"))
        self.change_text_color_button.setText(_("&Change"))
        self.reset_text_color_button.setText(_("Reset"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _("Colors and backgrounds"))
        self.label_11.setText(_("Page flip &duration:"))
        self.opt_page_flip_duration.setSpecialValueText(_("disabled"))
        self.opt_page_flip_duration.setSuffix(_(" secs"))
        self.opt_tap_flips_pages.setText(_("&Tapping on the page flips pages"))
        self.opt_wheel_flips_pages.setText(_("Mouse &wheel flips pages"))
        self.opt_line_scrolling_stops_on_pagebreaks.setText(_("Line &scrolling stops at page breaks"))
        self.groupBox.setTitle(_("Scrolling in flow mode"))
        self.label_29.setText(_("Control the amount the mouse &wheel scrolls:"))
        self.opt_wheel_scroll_fraction.setToolTip(_("This is a percentage, by making it less than 100 you can decrease the amount the wheel scrolls by, by making it more than 100 you can increase the scroll amount."))
        self.opt_wheel_scroll_fraction.setSuffix(_(" %"))
        self.label_30.setText(_("Control the amount the arrow &keys scroll:"))
        self.opt_line_scroll_fraction.setToolTip(_("This is a percentage, by making it less than 100 you can decrease the amount the arrow keys scroll by, by making it more than 100 you can increase the scroll amount."))
        self.opt_line_scroll_fraction.setSuffix(_(" %"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _("Page fl&ip/scrolling options"))
        self.hyphenate.setText(_("H&yphenate (break line in the middle of large words)"))
        self.hyphenate_label.setText(_("Default &language for hyphenation:"))
        self.hyphenate_default_lang.setToolTip(_("The default language to use for hyphenation rules. If the book does not specify a language, this will be used."))
        self.opt_show_controls.setText(_("Show &controls in the viewer window"))
        self.label_26.setText(_("Search &online URL:"))
        self.search_online_url.setToolTip(_("Change the search engine used to perform online searches for selected text.\n"
"You must enter the search URL for the search engine, with the placeholder\n"
"{text}, which will be replaced by the selected text."))
        self.opt_remember_window_size.setText(_("Remember last used &window size and layout"))
        self.opt_remember_current_page.setText(_("Remember the current &page when quitting"))
        self.opt_copy_bookmarks_to_file.setToolTip(_("Keep a copy of all bookmarks/current page information inside the e-book file, so that you can share them by simply sending the e-book file itself. Currently only works with e-books in the EPUB format."))
        self.opt_copy_bookmarks_to_file.setText(_("Keep a copy of &bookmarks/current page inside the e-book file, for easy sharing"))
        self.opt_singleinstance.setToolTip(_("Normally, you can view multiple books in calibre, each in its own viewer window. With this option, if you attempt to view a second book, it will replace the previously opened book instead of using a new window."))
        self.opt_singleinstance.setText(_("Allow only a single book to be &viewed at a time (needs restart)"))
        self.opt_fit_images.setText(_("&Resize images larger than the viewer window (needs restart)"))
        self.clear_search_history_button.setText(_("Clear search &history"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _("&Miscellaneous options"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _("&General"))
        self.label_9.setText(_("Double click to change a keyboard shortcut"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _("&Keyboard shortcuts"))
        self.label_10.setText(_("<p>A CSS stylesheet that can be used to control the look and feel of books. For examples, click <a href=\"https://www.mobileread.com/forums/showthread.php?t=51500\">here</a>."))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _("User &stylesheet"))
        self.label_23.setText(_("You can save and load the viewer settings as <i>themes</i>"))
        self.label_15.setText(_("Save current settings as a theme:"))
        self.save_theme_button.setText(_("&Save"))
        self.label_20.setText(_("Load a previously saved theme:"))
        self.load_theme_button.setText(_("&Load"))
        self.label_21.setText(_("Delete a saved theme:"))
        self.delete_theme_button.setText(_("&Delete"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _("&Theming"))
        self.label_25.setText(_("When you lookup a word, the viewer opens the word\'s definition in a dictionary website. The dictionary website is chosen based on the language of the book. You can customize the website used for a particular language here."))
        self.add_dictionary_website_button.setText(_("&Add website"))
        self.remove_dictionary_website_button.setText(_("&Remove website"))
        self.change_dictionary_website_button.setText(_("&Change website"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), _("&Dictionaries"))


