name: Transifex
on:
  push:
    branches: [master, ]


jobs:
    Push-To-Transifex:
        name: Update translations on Transifex
        if: github.repository == 'kovidgoyal/calibre'
        runs-on: ubuntu-latest
        container:
            image: 'archlinux/base:latest'
            env:
                CI: 'true'
        steps:
            - name: Prepare the container
              run: |
                pacman -Syu --noconfirm
                pacman -S --noconfirm tar

            - name: Checkout source code
              uses: actions/checkout@master
              with:
                fetch-depth: 2

            - name: Install calibre dependencies
              run: setup/arch-ci.sh

            - name: Install translations dependencies
              run: python -m pip install transifex-client

            - name: Bootstrap calibre
              run: runuser -u ci -- python setup.py bootstrap --ephemeral

            - name: Update translations
              env:
                tx: ${{ secrets.tx }}
              run: |
                  runuser -u ci -- python setup/unix-ci.py pot
